In [1]:
import pandas as pd

In [2]:
dtr=pd.read_csv("train2.csv")

In [3]:
print dtr

     Pclass   Age  SibSp  Parch      Fare Embarked   S   C   Q     Sex  male  \
0         3  22.0      1      0    7.2500        S NaN NaN NaN    male   NaN   
1         1  38.0      1      0   71.2833        C NaN NaN NaN  female   NaN   
2         3  26.0      0      0    7.9250        S NaN NaN NaN  female   NaN   
3         1  35.0      1      0   53.1000        S NaN NaN NaN  female   NaN   
4         3  35.0      0      0    8.0500        S NaN NaN NaN    male   NaN   
5         3   NaN      0      0    8.4583        Q NaN NaN NaN    male   NaN   
6         1  54.0      0      0   51.8625        S NaN NaN NaN    male   NaN   
7         3   2.0      3      1   21.0750        S NaN NaN NaN    male   NaN   
8         3  27.0      0      2   11.1333        S NaN NaN NaN  female   NaN   
9         2  14.0      1      0   30.0708        C NaN NaN NaN  female   NaN   
10        3   4.0      1      1   16.7000        S NaN NaN NaN  female   NaN   
11        1  58.0      0      0   26.550

In [5]:
dtr.fillna(value=0,inplace=True)

In [6]:
import numpy as np

In [7]:
df=np.array(dtr)

In [8]:
#One Hot Encodding Of Embarked and Sex and genearating sparce matrix
for i in range(0,len(df)):
    if df[i][5]=='S':
        df[i][6]=1
    elif df[i][5]=='C':
        df[i][7]=1
    elif df[i][5]=='Q':
        df[i][8]=1
for h in range(0,len(df)):
    if df[h][9]=='male':
        df[h][10]=1
    elif df[h][9]=='female':
        df[h][11]=1

In [9]:
df

array([[3L, 22.0, 1L, ..., 1, 0.0, 0L],
       [1L, 38.0, 1L, ..., 0.0, 1, 1L],
       [3L, 26.0, 0L, ..., 0.0, 1, 1L],
       ..., 
       [3L, 0.0, 1L, ..., 0.0, 1, 0L],
       [1L, 26.0, 0L, ..., 1, 0.0, 1L],
       [3L, 32.0, 0L, ..., 1, 0.0, 0L]], dtype=object)

In [10]:
X=np.delete(df,[5,9,12],axis=1)
y=np.delete(df,[0,1,2,3,4,5,6,7,8,9,10,11],axis=1)

In [11]:
X

array([[3L, 22.0, 1L, ..., 0.0, 1, 0.0],
       [1L, 38.0, 1L, ..., 0.0, 0.0, 1],
       [3L, 26.0, 0L, ..., 0.0, 0.0, 1],
       ..., 
       [3L, 0.0, 1L, ..., 0.0, 0.0, 1],
       [1L, 26.0, 0L, ..., 0.0, 1, 0.0],
       [3L, 32.0, 0L, ..., 1, 1, 0.0]], dtype=object)

In [12]:
y

array([[0L],
       [1L],
       [1L],
       [1L],
       [0L],
       [0L],
       [0L],
       [0L],
       [1L],
       [1L],
       [1L],
       [1L],
       [0L],
       [0L],
       [0L],
       [1L],
       [0L],
       [1L],
       [0L],
       [1L],
       [0L],
       [1L],
       [1L],
       [1L],
       [0L],
       [1L],
       [0L],
       [0L],
       [1L],
       [0L],
       [0L],
       [1L],
       [1L],
       [0L],
       [0L],
       [0L],
       [1L],
       [0L],
       [0L],
       [1L],
       [0L],
       [0L],
       [0L],
       [1L],
       [1L],
       [0L],
       [0L],
       [1L],
       [0L],
       [0L],
       [0L],
       [0L],
       [1L],
       [1L],
       [0L],
       [1L],
       [1L],
       [0L],
       [1L],
       [0L],
       [0L],
       [1L],
       [0L],
       [0L],
       [0L],
       [1L],
       [1L],
       [0L],
       [1L],
       [0L],
       [0L],
       [0L],
       [0L],
       [0L],
       [1L],
       [0L],
       [0L],

In [13]:
#Preparing Training and Testing data
X_train=X[:847]
X_test=X[847:]
y_train=y[:847]
y_test=y[847:]

In [14]:
X_train

array([[3L, 22.0, 1L, ..., 0.0, 1, 0.0],
       [1L, 38.0, 1L, ..., 0.0, 0.0, 1],
       [3L, 26.0, 0L, ..., 0.0, 0.0, 1],
       ..., 
       [3L, 17.0, 0L, ..., 0.0, 1, 0.0],
       [3L, 42.0, 0L, ..., 0.0, 1, 0.0],
       [3L, 0.0, 8L, ..., 0.0, 1, 0.0]], dtype=object)

In [15]:
X_test

array([[3L, 35.0, 0L, 0L, 7.8958, 0.0, 1, 0.0, 1, 0.0],
       [2L, 28.0, 0L, 1L, 33.0, 1, 0.0, 0.0, 1, 0.0],
       [1L, 0.0, 1L, 0L, 89.1042, 0.0, 1, 0.0, 0.0, 1],
       [3L, 4.0, 4L, 2L, 31.275, 1, 0.0, 0.0, 1, 0.0],
       [3L, 74.0, 0L, 0L, 7.775, 1, 0.0, 0.0, 1, 0.0],
       [3L, 9.0, 1L, 1L, 15.2458, 0.0, 1, 0.0, 0.0, 1],
       [1L, 16.0, 0L, 1L, 39.4, 1, 0.0, 0.0, 0.0, 1],
       [2L, 44.0, 1L, 0L, 26.0, 1, 0.0, 0.0, 0.0, 1],
       [3L, 18.0, 0L, 1L, 9.35, 1, 0.0, 0.0, 0.0, 1],
       [1L, 45.0, 1L, 1L, 164.8667, 1, 0.0, 0.0, 0.0, 1],
       [1L, 51.0, 0L, 0L, 26.55, 1, 0.0, 0.0, 1, 0.0],
       [3L, 24.0, 0L, 3L, 19.2583, 0.0, 1, 0.0, 0.0, 1],
       [3L, 0.0, 0L, 0L, 7.2292, 0.0, 1, 0.0, 1, 0.0],
       [3L, 41.0, 2L, 0L, 14.1083, 1, 0.0, 0.0, 1, 0.0],
       [2L, 21.0, 1L, 0L, 11.5, 1, 0.0, 0.0, 1, 0.0],
       [1L, 48.0, 0L, 0L, 25.9292, 1, 0.0, 0.0, 0.0, 1],
       [3L, 0.0, 8L, 2L, 69.55, 1, 0.0, 0.0, 0.0, 1],
       [2L, 24.0, 0L, 0L, 13.0, 1, 0.0, 0.0, 1, 0.0],
     

In [16]:
y_train

array([[0L],
       [1L],
       [1L],
       [1L],
       [0L],
       [0L],
       [0L],
       [0L],
       [1L],
       [1L],
       [1L],
       [1L],
       [0L],
       [0L],
       [0L],
       [1L],
       [0L],
       [1L],
       [0L],
       [1L],
       [0L],
       [1L],
       [1L],
       [1L],
       [0L],
       [1L],
       [0L],
       [0L],
       [1L],
       [0L],
       [0L],
       [1L],
       [1L],
       [0L],
       [0L],
       [0L],
       [1L],
       [0L],
       [0L],
       [1L],
       [0L],
       [0L],
       [0L],
       [1L],
       [1L],
       [0L],
       [0L],
       [1L],
       [0L],
       [0L],
       [0L],
       [0L],
       [1L],
       [1L],
       [0L],
       [1L],
       [1L],
       [0L],
       [1L],
       [0L],
       [0L],
       [1L],
       [0L],
       [0L],
       [0L],
       [1L],
       [1L],
       [0L],
       [1L],
       [0L],
       [0L],
       [0L],
       [0L],
       [0L],
       [1L],
       [0L],
       [0L],

In [17]:
y_test

array([[0L],
       [0L],
       [1L],
       [0L],
       [0L],
       [0L],
       [1L],
       [0L],
       [1L],
       [1L],
       [1L],
       [1L],
       [0L],
       [0L],
       [0L],
       [1L],
       [0L],
       [0L],
       [1L],
       [1L],
       [0L],
       [0L],
       [1L],
       [0L],
       [1L],
       [0L],
       [0L],
       [1L],
       [1L],
       [0L],
       [0L],
       [0L],
       [1L],
       [1L],
       [0L],
       [0L],
       [0L],
       [0L],
       [0L],
       [0L],
       [1L],
       [0L],
       [1L],
       [0L]], dtype=object)

In [18]:
#Linear Regression on the DataSet


In [19]:
from sklearn import *
lreg = linear_model.LinearRegression()
lreg.fit(X_train,y_train)

C:\Users\SACHIN\Anaconda2\lib\site-packages\sklearn\cross_validation.py:44: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)
C:\Users\SACHIN\Anaconda2\lib\site-packages\sklearn\grid_search.py:43: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. This module will be removed in 0.20.
  DeprecationWarning)
C:\Users\SACHIN\Anaconda2\lib\site-packages\sklearn\lda.py:6: DeprecationWarning: lda.LDA has been moved to discriminant_analysis.LinearDiscriminantAnalysis in 0.17 and will be removed in 0.19
  "in 0.17 and will be removed in 0.19", DeprecationWarning)
C:\Users\SACHIN\An

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [20]:
print "Regression Cofficient /n",lreg.coef_

Regression Cofficient /n [[-0.15361615 -0.00260762 -0.03636885 -0.00483476  0.0003434  -0.12209126
  -0.06785845 -0.09783886 -0.25808667  0.25808667]]


In [21]:
print "Predrction /n ",lreg.predict(X_test)

Predrction /n  [[ 0.12308959]
 [ 0.24451237]
 [ 1.02928032]
 [ 0.00257666]
 [-0.03288206]
 [ 0.66838155]
 [ 0.94779111]
 [ 0.6850258 ]
 [ 0.62502434]
 [ 0.87888662]
 [ 0.34077297]
 [ 0.65734442]
 [ 0.21412753]
 [-0.0173933 ]
 [ 0.2238485 ]
 [ 0.86455599]
 [ 0.39684877]
 [ 0.25290959]
 [ 0.72214568]
 [ 0.77941875]
 [ 0.40114849]
 [ 0.16067452]
 [ 0.10960129]
 [ 0.0923254 ]
 [ 0.83510308]
 [ 0.38030991]
 [ 0.03794447]
 [ 0.7802938 ]
 [ 0.69118506]
 [ 0.10864078]
 [ 0.11057877]
 [ 0.16012363]
 [ 0.91274562]
 [ 0.76610476]
 [ 0.07407202]
 [ 0.61982925]
 [ 0.24162059]
 [ 0.09464257]
 [ 0.58196837]
 [ 0.24508671]
 [ 0.94157502]
 [ 0.63559994]
 [ 0.46138113]
 [ 0.10088198]]


In [26]:
print "Prediction after round /n",np.round((lreg.predict(X_test)))

Prediction after round /n [[ 0.]
 [ 0.]
 [ 1.]
 [ 0.]
 [ 0.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 0.]
 [ 1.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 1.]
 [ 0.]
 [ 0.]
 [ 1.]
 [ 1.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 1.]
 [ 0.]
 [ 0.]
 [ 1.]
 [ 1.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 1.]
 [ 1.]
 [ 0.]
 [ 1.]
 [ 0.]
 [ 0.]
 [ 1.]
 [ 0.]
 [ 1.]
 [ 1.]
 [ 0.]
 [ 0.]]


In [27]:
print "Score ",lreg.score(X_test,y_test)

Score  0.506777384437


In [28]:
#Converting the numpy array to list
X_train=X_train.tolist()
y_train=y_train.tolist()
X_test=X_test.tolist()
y_test=y_test.tolist()

In [30]:
#KNN classifier
from sklearn.neighbors import KNeighborsClassifier
knncls = KNeighborsClassifier()
knncls.fit(X_train,y_train)
print "KNN prediction /n ",(knncls.predict(X_test))

C:\Users\SACHIN\Anaconda2\lib\site-packages\ipykernel_launcher.py:4: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  after removing the cwd from sys.path.


KNN prediction /n  [0 1 1 0 0 1 0 1 1 1 1 1 0 0 0 1 0 0 1 0 1 0 1 0 1 0 0 1 1 0 0 0 1 0 0 0 0
 0 0 0 1 1 1 0]


In [32]:
"Score for Knn Classifier ",knncls.score(X_test,y_test)

('Score for Knn Classifier ', 0.81818181818181823)

In [34]:
svmclf = svm.SVC()
svmclf.fit(X_train,y_train)
print "SVM prediction /n",svmclf.predict(X_test)

C:\Users\SACHIN\Anaconda2\lib\site-packages\sklearn\utils\validation.py:526: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVM prediction /n [0 1 1 1 0 1 0 0 1 1 1 1 0 0 0 1 0 0 1 1 0 0 1 0 1 0 0 0 1 0 0 0 1 0 0 0 0
 0 0 0 1 1 1 0]


In [35]:
"Score for SVM Classifier ",svmclf.score(X_test,y_test)

('Score for SVM Classifier ', 0.84090909090909094)